kafka:
  brokers:
    - 127.0.0.1:9092
  topics:
    - name: payment_events
      groups:
        - name: payment_processor
          alert_threshold: 0  # 告警阈值（消息数）
          is_notify: false
        - name: fraud_detection
          alert_threshold: 100
          is_notify: false
      notify_list:
        - hudengjin
    - name: user_activity
      groups:
        - name: analytics
          alert_threshold: 100
          is_notify: false
      notify_list:
        - hudengjin

alert:
  api_url: "http://198.3.100.93:18088/dmm/sendMsg"  # 告警API地址
  retry_times: 3  # API调用重试次数
  timeout: 5s     # API调用超时时间

mysql:
  host: "127.0.0.1:3306"
  database: "kafka_monitor"
  username: "hudengjin"
  password: "hudengjin"
  table: "consumer_lag_logs"  # 监控数据表名

monitor:
  interval_seconds: 10

logging:
  level: info
  format: console # console / json
  output_path: "logs/app.log"
  rotation:
    max_size: 100 # MB
    max_backups: 5
    max_age: 7 # days
    compress: true
